# -*- coding: utf-8 -*-
"""myAssignment-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VpDJWwxqVEQU_hNduwfwXO8mC_mrEVO1

Assignment-1
"""

#Day-1
#Assignment-1
#Date:28/06/2021
#Amal V.V
#amalvv2000cit@gmail.com

"""**   CALCULATOR**"""

a= int(input("Enter the first number :"))
b= int(input("Enter the second number :"))
Addition = a + b
Subtraction = a - b
Multiplication = a * b
Division = a/b
print("The Addition value is :", Addition)
print("The subtracted value is :", Subtraction)
print("The multipiled value is : ", Multiplication)
print("The divisoned value is :", Division)

